#%RAML 1.0 DataType

description: This object represents an incoming update. At most one of the optional parameters can be present in any given update.
type: object
properties:
  update_id:
    description: 	The update's unique identifier. Update identifiers start from a certain positive number and increase sequentially. This ID becomes especially handy if you're using Webhooks, since it allows you to ignore repeated updates or to restore the correct update sequence, should they get out of order. If there are no new updates for at least a week, then identifier of the next update will be chosen randomly instead of sequentially.
    type:	integer
    required: true
    
  message?:
    description: New incoming message of any kind — text, photo, sticker, etc.
    type:	!include Message.raml
    
  edited_message?:
    description: New version of a message that is known to the bot and was edited
    type:	!include Message.raml

  channel_post?:
    description: New incoming channel post of any kind — text, photo, sticker, etc.
    type:	!include Message.raml

  edited_channel_post?:
    description: New version of a channel post that is known to the bot and was edited
    type:	!include Message.raml
